run_name: Zjets_real_50Ke

dataset_params:
  type: Z_2j_dataset
  path: /Users/huetsch/Desktop/data/Omnifold.npz
  path_gen: /remote/gpu07/huetsch/data/Z_2j_Gen.npy
  path_sim: /remote/gpu07/huetsch/data/Z_2j_Sim.npy

  n_train: 150000
  n_test: 150000

model_params:
  type: CFM
  hidden_layers: 8
  internal_size: 512
  lr: 1.e-3
  n_epochs: 50000
  batch_size: 16384
  batch_size_sample: 10000

  cond_x1: False
  noise_scale: 0.001
  n_steps: 1000
